name: SkyblockDamage
version: 0.5
main: me.sql.skyblockdamage.SkyblockDamage
authors: [ imSQL ]
description: Implements Damage as it is in Hypixel SkyBlock
website: https://www.youtube.com/channel/UC41tJpxv_0TWrdUqw3nAKdw
depend:
    - SkyblockMobs
commands:
  skyblockdamage:
    description: Skyblock Damage
    aliases: [sbd, sbdamage]
    permission: sbdamage.sbd
    permission-message: §cThis command doesn't exist, or you don't have permission to use it.
    usage: "&cUsage: /<command> [about/help]"
permissions:
  sbdamage.sbd:
    description: Allows you to use and interact with the SkyblockDamage Plugin.
    default: op
  sbdamage.*:
    children:
        - sbdamage.sbd


