name: SkyblockItems
version: 0.1
main: me.sql.skyblockitems.SkyblockItems
author: imSQL
description: Implements items as they are in Hypixel SkyBlock
website: https://www.youtube.com/channel/UC41tJpxv_0TWrdUqw3nAKdw
commands: 
    skyblockitems:
        description: Skyblock Items
        alias: [sbi,sbitems]
        permission: sbitems.sbi
        permission-message: §cThis command doesn't exist, or you don't have permission to use it.
        Usage: "§cUsage: /<command> [about/help/createitem/deleteitem]"
    sbitem:
        description: Gives you a custom item
        permission: sbitems.sbitem
        permission-message: §cThis command doesn't exist, or you don't have permission to use it.
        Usage: "§cUsage: /<command> [Custom Item name]"
permissions:
    sbitems.sbi:
        description: "Allows you to use and interact with the SkyblockItems plugin."
        default: op
    sbitems.sbitem:
        description: "Allows you to give yourself custom items."
        default: op
    sbitems.*:
        children:
            - sbitems.sbitem
            - sbitems.sbi